name: SimpleCommandBlocker
main: me.vitikc.scb.Main
version: 1.3.1
commands:
    scb:
        description: Shows information about plugin
        usage: /<command>
    scb add:
        description: Blocks command
        usage: /<command> command
    scb remove:
        description: Unlocks command
        usage: /<command> command
    scb list:
        description: Shows list of blocked commands
        usage: /<command>
    scb reload:
        description: Reloads data
        usage: /<command>